### ISSUE TITLE
renderRicv gives weird output

### ISSUE THREAD

**Issue by jebyrnes** [xvrdm/ricv#4]
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/757410/160409185-7f817fc3-ddb4-46ac-94b2-a13ae36b6d22.png">

So, I made a bunch of equal-sized jpgs from ggplots and want to use ricv to view them. Here's my UI code.

```
         tabPanel("Compare Years",
               sidebarLayout(
                 sidebarPanel(width=2,
                              radioButtons(inputId = "start_year",
                                           "Start Year",
                                           choices = years[!is.na(years)],
                                           selected = 1982),

                              radioButtons(inputId = "end_year",
                                           "End Year",
                                           choices = years[!is.na(years)],
                                           selected = 2014)
                              ),
                 mainPanel(
                   ricvOutput("compare_years")
                 )
               )
          ),
```

And then in my server

```
  output$compare_years <- renderRicv({
    ricv(
      img1 = glue("figures/{input$start_year}.jpg"),
      img2 = glue("figures/{input$end_year}.jpg"),
      options = list(addCircle = T, hoverStart = T)
    )
    })
```

BUT - I get this weird monstrosity where the left hand side shows the original image (it doesn't change, no matter how I change the radio buttons) at a HUGE size. The right hand size shows a properly sized image, and if I swipe back and forth across it, I get proper behavior. ALthough the updating seems to be stochastic on which side is updating?  Not sure what is going on here.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/757410/160409781-baa9eb1c-1bf5-4e41-bd2c-62ad429b2c38.png">

**Comment by jebyrnes** [comment]
Note: adding both a height and width argument to render and setting them to 100% fixed this. Perhaps this should be the default?

**Comment by jebyrnes** [comment]
Oh! Nope! Now changing one of those radio buttons makes the images go away? Uh oh........

**Comment by jebyrnes** [comment]
See https://shiny.umb.edu/shiny/users/jarrett.byrnes/borror_algae_maps_shiny/ for behavior and https://github.com/Intertidal-Subtidal-WG/borror_algae_maps_shiny/blob/main/app.R if you want to look more at the code.

**Comment by xvrdm** [comment]
Will have a look later today, thanks.

**Comment by jebyrnes** [comment]
Thx!

**Comment by xvrdm** [comment]
Unfortunately, I have a hard time installing the whole geographical packages stack on my current linux machine. 

However, I could reproduce the bug with the minimal example in https://github.com/xvrdm/ricv/tree/main/tests/testshiny . It looks like setting `fluidMode=T` in the options fixes the issue. Could you please try it?

**Comment by jebyrnes** [comment]
Huh - so, these images are large.....and it seems like adding the above leads to weird behavior. Not showing initial images and then showing HUGE images that don't fit later. See https://shiny.umb.edu/shiny/users/jarrett.byrnes/borror_algae_maps_shiny/

**Comment by jebyrnes** [comment]
Currently

```
  output$compare_years <- renderRicv({
    ricv(
      img1 = glue("figures/{input$start_year}.jpg"),
      img2 = glue("figures/{input$end_year}.jpg"),
      options = list(addCircle = T, hoverStart = T, fluidMode=T)
    )
  })
```

**Comment by jebyrnes** [comment]
OK - I fixed it by manually resizing the images and then giving `ricvOutput` the same width and height. Might want to be something you check for programatically or include this in the examples.

**Comment by xvrdm** [comment]
Does that mean that you can only have square image (same width/height)?

**Comment by jebyrnes** [comment]
Yes. I made the width and height of the image the same as the width and height in ricvOutput, and that fixed the issue, but, a hair wonky to have to remember that.....

**Comment by jebyrnes** [comment]
To fix the issue, I had to both specify sizes in the output

```
               ricvOutput("compare_years", 
                          width = "800px", 
                          height = "600px"
                          )
```

and set the output to fluidMode

```
  output$compare_years <- renderRicv({
    ricv(
      img1 = glue("figures/{input$start_year}.jpg"),
      img2 = glue("figures/{input$end_year}.jpg"),
      options = list(addCircle = T, hoverStart = T, fluidMode=T)
    )
  })
```
